name: Browser tests

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    symfony-cache:
        name: "Symfony Cache integration tests"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            project-version: '^3.3.x-dev'
            test-suite: '--mode=standard --profile=httpCache --suite=symfonycache'
            test-setup-phase-1:  '--mode=standard --profile=httpCache --suite=setup-symfony-cache'
            test-setup-phase-2: '--mode=standard --profile=httpCache --suite=setup'
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    varnish6:
        name: "Varnish 6 integration tests"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            project-version: '^3.3.x-dev'
            setup: "doc/docker/base-dev.yml:doc/docker/varnish.yml:doc/docker/selenium.yml"
            test-suite:  '--mode=standard --profile=httpCache --suite=varnish6'
            test-setup-phase-1: '--mode=standard --profile=httpCache --suite=setup'
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    varnish7:
        name: "Varnish 7 integration tests"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            project-version: '^3.3.x-dev'
            setup: "doc/docker/base-dev.yml:doc/docker/varnish7.yml:doc/docker/selenium.yml"
            test-suite:  '--mode=standard --profile=httpCache --suite=varnish7'
            test-setup-phase-1: '--mode=standard --profile=httpCache --suite=setup'
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    varnish6-translation-aware:
        name: "Varnish integration tests (translation-aware)"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            project-version: '^3.3.x-dev'
            setup: "doc/docker/base-dev.yml:doc/docker/varnish.yml:doc/docker/selenium.yml"
            test-suite:  '--mode=standard --profile=httpCache --suite=varnish6-translation-aware'
            test-setup-phase-1: '--mode=standard --profile=httpCache --suite=setup-translation-aware'
            test-setup-phase-2: '--mode=standard --profile=httpCache --suite=setup'
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    varnish7-translation-aware:
        name: "Varnish 7 integration tests (translation-aware)"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            project-version: '^3.3.x-dev'
            setup: "doc/docker/base-dev.yml:doc/docker/varnish7.yml:doc/docker/selenium.yml"
            test-suite:  '--mode=standard --profile=httpCache --suite=varnish7-translation-aware'
            test-setup-phase-1: '--mode=standard --profile=httpCache --suite=setup-translation-aware'
            test-setup-phase-2: '--mode=standard --profile=httpCache --suite=setup'
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    varnish6-token:
        name: "Varnish 6 integration tests with invalidate token"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            project-version: '^3.3.x-dev'
            setup: "doc/docker/base-dev.yml:doc/docker/varnish.yml:doc/docker/selenium.yml"
            test-suite:  '--mode=standard --profile=httpCache --suite=varnish6'
            test-setup-phase-1: '--mode=standard --profile=httpCache --suite=setup-token'
            test-setup-phase-2: '--mode=standard --profile=httpCache --suite=setup'
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    varnish7-token:
        name: "Varnish 7 integration tests with invalidate token"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            project-version: '^3.3.x-dev'
            setup: "doc/docker/base-dev.yml:doc/docker/varnish7.yml:doc/docker/selenium.yml"
            test-suite:  '--mode=standard --profile=httpCache --suite=varnish7'
            test-setup-phase-1: '--mode=standard --profile=httpCache --suite=setup-token'
            test-setup-phase-2: '--mode=standard --profile=httpCache --suite=setup'
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
